template:
  - sensor:
      - name: "swiatlo drzwi lazienka"
        state: |-
          {% if states('light.pasek_led') == 'on' and states('binary_sensor.drzwi_lazienka') == 'on' %}
          Otwarte-Zapalone
          {% elif states('light.pasek_led') == 'off' and states('binary_sensor.drzwi_lazienka') == 'on' %}
          Otwarte-Zgaszone
          {% elif states('binary_sensor.drzwi_lazienka') == 'off' %}
          Zamkniete
          {% endif %}
